str=" I am a Good Boy"
print(str)
print(str[1])
print(str[0:5])
print(str[0:19])
print(str[0:19:2])
print(len(str))
print(str[:19])
print(str[:])
print(str[-7:-2])
print(str[::-1])
print(str.isalnum())
print(str.isalpha())
print(str.endswith("Boy"))
print(str.lower())
print(str.upper())